# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_animus_client_py3')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_animus_client_py3')
    _animus_client_py3 = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_animus_client_py3', [dirname(__file__)])
        except ImportError:
            import _animus_client_py3
            return _animus_client_py3
        try:
            _mod = imp.load_module('_animus_client_py3', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _animus_client_py3 = swig_import_helper()
    del swig_import_helper
else:
    import _animus_client_py3
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class _GoString_(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, _GoString_, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, _GoString_, name)
    __repr__ = _swig_repr
    __swig_setmethods__["p"] = _animus_client_py3._GoString__p_set
    __swig_getmethods__["p"] = _animus_client_py3._GoString__p_get
    if _newclass:
        p = _swig_property(_animus_client_py3._GoString__p_get, _animus_client_py3._GoString__p_set)
    __swig_setmethods__["n"] = _animus_client_py3._GoString__n_set
    __swig_getmethods__["n"] = _animus_client_py3._GoString__n_get
    if _newclass:
        n = _swig_property(_animus_client_py3._GoString__n_get, _animus_client_py3._GoString__n_set)

    def __init__(self):
        this = _animus_client_py3.new__GoString_()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _animus_client_py3.delete__GoString_
    __del__ = lambda self: None
_GoString__swigregister = _animus_client_py3._GoString__swigregister
_GoString__swigregister(_GoString_)

class GoInterface(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GoInterface, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GoInterface, name)
    __repr__ = _swig_repr
    __swig_setmethods__["t"] = _animus_client_py3.GoInterface_t_set
    __swig_getmethods__["t"] = _animus_client_py3.GoInterface_t_get
    if _newclass:
        t = _swig_property(_animus_client_py3.GoInterface_t_get, _animus_client_py3.GoInterface_t_set)
    __swig_setmethods__["v"] = _animus_client_py3.GoInterface_v_set
    __swig_getmethods__["v"] = _animus_client_py3.GoInterface_v_get
    if _newclass:
        v = _swig_property(_animus_client_py3.GoInterface_v_get, _animus_client_py3.GoInterface_v_set)

    def __init__(self):
        this = _animus_client_py3.new_GoInterface()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _animus_client_py3.delete_GoInterface
    __del__ = lambda self: None
GoInterface_swigregister = _animus_client_py3.GoInterface_swigregister
GoInterface_swigregister(GoInterface)

class GoSlice(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GoSlice, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GoSlice, name)
    __repr__ = _swig_repr
    __swig_setmethods__["data"] = _animus_client_py3.GoSlice_data_set
    __swig_getmethods__["data"] = _animus_client_py3.GoSlice_data_get
    if _newclass:
        data = _swig_property(_animus_client_py3.GoSlice_data_get, _animus_client_py3.GoSlice_data_set)
    __swig_setmethods__["len"] = _animus_client_py3.GoSlice_len_set
    __swig_getmethods__["len"] = _animus_client_py3.GoSlice_len_get
    if _newclass:
        len = _swig_property(_animus_client_py3.GoSlice_len_get, _animus_client_py3.GoSlice_len_set)
    __swig_setmethods__["cap"] = _animus_client_py3.GoSlice_cap_set
    __swig_getmethods__["cap"] = _animus_client_py3.GoSlice_cap_get
    if _newclass:
        cap = _swig_property(_animus_client_py3.GoSlice_cap_get, _animus_client_py3.GoSlice_cap_set)

    def __init__(self):
        this = _animus_client_py3.new_GoSlice()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _animus_client_py3.delete_GoSlice
    __del__ = lambda self: None
GoSlice_swigregister = _animus_client_py3.GoSlice_swigregister
GoSlice_swigregister(GoSlice)


def Version():
    return _animus_client_py3.Version()
Version = _animus_client_py3.Version

def LoginUser(p0, p1, p2):
    return _animus_client_py3.LoginUser(p0, p1, p2)
LoginUser = _animus_client_py3.LoginUser

def GetRobots(p0, p1, p2):
    return _animus_client_py3.GetRobots(p0, p1, p2)
GetRobots = _animus_client_py3.GetRobots

def Connect(p0):
    return _animus_client_py3.Connect(p0)
Connect = _animus_client_py3.Connect

def OpenModality(p0, p1, p2):
    return _animus_client_py3.OpenModality(p0, p1, p2)
OpenModality = _animus_client_py3.OpenModality

def SetModality(p0, p1, p2, p3):
    return _animus_client_py3.SetModality(p0, p1, p2, p3)
SetModality = _animus_client_py3.SetModality

def SetModalityPtr(p0, p1, p2, p3, p4, p5):
    return _animus_client_py3.SetModalityPtr(p0, p1, p2, p3, p4, p5)
SetModalityPtr = _animus_client_py3.SetModalityPtr

def GetModalityPtr(p0, p1):
    return _animus_client_py3.GetModalityPtr(p0, p1)
GetModalityPtr = _animus_client_py3.GetModalityPtr

def GetModality(p0, p1):
    return _animus_client_py3.GetModality(p0, p1)
GetModality = _animus_client_py3.GetModality

def CloseModality(p0, p1):
    return _animus_client_py3.CloseModality(p0, p1)
CloseModality = _animus_client_py3.CloseModality

def Disconnect(p0):
    return _animus_client_py3.Disconnect(p0)
Disconnect = _animus_client_py3.Disconnect

def CloseClientInterface():
    return _animus_client_py3.CloseClientInterface()
CloseClientInterface = _animus_client_py3.CloseClientInterface

def SetModalityPtr_wrapper(p0, p1, p2, p3, p4, p5):
    return _animus_client_py3.SetModalityPtr_wrapper(p0, p1, p2, p3, p4, p5)
SetModalityPtr_wrapper = _animus_client_py3.SetModalityPtr_wrapper
# This file is compatible with both classic and new-style classes.


